name: space_x_launches
description: Project for TBR Group.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0-245.0.dev <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  provider: ^6.0.5
  very_good_analysis: ^4.0.0+1
  http: ^0.13.6
  intl: ^0.18.1
  bloc: ^8.1.2
  equatable: ^2.0.5
  flutter_bloc: ^8.1.3
  url_launcher: ^6.1.4

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

  assets:
    - assets/images/

